-- ========================================
-- guitolua v10.1.0
-- GUI / INSTANCE -> LUAU
-- ========================================

local Players = game:GetService("Players")
local CollectionService = game:GetService("CollectionService")

local ExeUI = Instance.new("ScreenGui")
local ClearBTN = Instance.new("TextButton")
local UIGradient = Instance.new("UIGradient")
local InjectbackBTN = Instance.new("TextButton")
local ShhBTN = Instance.new("TextButton")
local TextBox = Instance.new("TextBox")
local EXEBTN = Instance.new("TextButton")
local InjectSafeBTN = Instance.new("TextButton")
local UIDragDetector = Instance.new("UIDragDetector")

ExeUI.Archivable = true
ExeUI.Enabled = true
ExeUI.DisplayOrder = 0
ExeUI.IgnoreGuiInset = false
ExeUI.ResetOnSpawn = false
ExeUI.SafeAreaCompatibility = Enum.SafeAreaCompatibility.FullscreenExtension
ExeUI.ScreenInsets = Enum.ScreenInsets.CoreUISafeInsets
ExeUI.ZIndexBehavior = Enum.ZIndexBehavior.Global

local Frame = Instance.new("Frame")
Frame.Archivable = true
Frame.Active = false
Frame.Parent = ExeUI
Frame.Name = "Frame"
Frame.AnchorPoint = Vector2.new(0, 0)
Frame.AutomaticSize = Enum.AutomaticSize.None
Frame.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Frame.BackgroundTransparency = 0
Frame.BorderColor3 = Color3.fromRGB(0, 0, 0)
Frame.BorderMode = Enum.BorderMode.Outline
Frame.BorderSizePixel = 1
Frame.ClipsDescendants = false
Frame.Interactable = true
Frame.LayoutOrder = 0
Frame.Position = UDim2.new(0.12591633200645447, 0, 0.010416666977107525, 0)
Frame.Rotation = 0
Frame.Selectable = false
Frame.SelectionOrder = 0
Frame.Size = UDim2.new(0.77422291040420532, 0, 0.9672619104385376, 0)
Frame.SizeConstraint = Enum.SizeConstraint.RelativeXY
Frame.Visible = true
Frame.ZIndex = 1

ClearBTN.Archivable = true
ClearBTN.Active = true
ClearBTN.AnchorPoint = Vector2.new(0, 0)
ClearBTN.AutomaticSize = Enum.AutomaticSize.None
ClearBTN.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
ClearBTN.BackgroundTransparency = 0
ClearBTN.BorderColor3 = Color3.fromRGB(0, 0, 0)
ClearBTN.BorderMode = Enum.BorderMode.Outline
ClearBTN.BorderSizePixel = 1
ClearBTN.ClipsDescendants = false
ClearBTN.Interactable = true
ClearBTN.LayoutOrder = 0
ClearBTN.Position = UDim2.new(0.39837822318077087, 0, 0.71384614706039429, 0)
ClearBTN.Rotation = 0
ClearBTN.Selectable = true
ClearBTN.SelectionOrder = 0
ClearBTN.Size = UDim2.new(0.31207844614982605, 0, 0.23692312836647034, 0)
ClearBTN.SizeConstraint = Enum.SizeConstraint.RelativeXY
ClearBTN.Visible = true
ClearBTN.ZIndex = 1
ClearBTN.Font = Enum.Font.Bodoni
ClearBTN.LineHeight = 1
ClearBTN.MaxVisibleGraphemes = -1
ClearBTN.RichText = false
ClearBTN.Text = "Clear"
ClearBTN.TextColor3 = Color3.fromRGB(0, 0, 0)
ClearBTN.TextScaled = true
ClearBTN.TextSize = 8
ClearBTN.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
ClearBTN.TextStrokeTransparency = 1
ClearBTN.TextTransparency = 0
ClearBTN.TextTruncate = Enum.TextTruncate.None
ClearBTN.TextWrapped = true
ClearBTN.TextXAlignment = Enum.TextXAlignment.Center
ClearBTN.TextYAlignment = Enum.TextYAlignment.Center
ClearBTN.AutoButtonColor = true
ClearBTN.Modal = false
ClearBTN.Style = Enum.ButtonStyle.Custom

UIGradient.Archivable = true
UIGradient.Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 255, 255)), ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 255, 255))})
UIGradient.Enabled = true
UIGradient.Offset = Vector2.new(0, 0)
UIGradient.Rotation = 0
UIGradient.Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 0, 0), NumberSequenceKeypoint.new(1, 0, 0)})

InjectbackBTN.Archivable = true
InjectbackBTN.Active = true
InjectbackBTN.AnchorPoint = Vector2.new(0, 0)
InjectbackBTN.AutomaticSize = Enum.AutomaticSize.None
InjectbackBTN.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
InjectbackBTN.BackgroundTransparency = 0
InjectbackBTN.BorderColor3 = Color3.fromRGB(0, 0, 0)
InjectbackBTN.BorderMode = Enum.BorderMode.Outline
InjectbackBTN.BorderSizePixel = 1
InjectbackBTN.ClipsDescendants = false
InjectbackBTN.Interactable = true
InjectbackBTN.LayoutOrder = 0
InjectbackBTN.Position = UDim2.new(0.79330557584762573, 0, 0.4046153724193573, 0)
InjectbackBTN.Rotation = 0
InjectbackBTN.Selectable = true
InjectbackBTN.SelectionOrder = 0
InjectbackBTN.Size = UDim2.new(0.19288010895252228, 0, 0.29076939821243286, 0)
InjectbackBTN.SizeConstraint = Enum.SizeConstraint.RelativeXY
InjectbackBTN.Visible = true
InjectbackBTN.ZIndex = 1
InjectbackBTN.Font = Enum.Font.Bodoni
InjectbackBTN.LineHeight = 1
InjectbackBTN.MaxVisibleGraphemes = -1
InjectbackBTN.RichText = false
InjectbackBTN.Text = "Inject backdoor safe"
InjectbackBTN.TextColor3 = Color3.fromRGB(0, 0, 0)
InjectbackBTN.TextScaled = true
InjectbackBTN.TextSize = 8
InjectbackBTN.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
InjectbackBTN.TextStrokeTransparency = 1
InjectbackBTN.TextTransparency = 0
InjectbackBTN.TextTruncate = Enum.TextTruncate.None
InjectbackBTN.TextWrapped = true
InjectbackBTN.TextXAlignment = Enum.TextXAlignment.Center
InjectbackBTN.TextYAlignment = Enum.TextYAlignment.Center
InjectbackBTN.AutoButtonColor = true
InjectbackBTN.Modal = false
InjectbackBTN.Style = Enum.ButtonStyle.Custom

ShhBTN.Archivable = true
ShhBTN.Active = true
ShhBTN.AnchorPoint = Vector2.new(0, 0)
ShhBTN.AutomaticSize = Enum.AutomaticSize.None
ShhBTN.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
ShhBTN.BackgroundTransparency = 0
ShhBTN.BorderColor3 = Color3.fromRGB(0, 0, 0)
ShhBTN.BorderMode = Enum.BorderMode.Outline
ShhBTN.BorderSizePixel = 1
ShhBTN.ClipsDescendants = false
ShhBTN.Interactable = true
ShhBTN.LayoutOrder = 0
ShhBTN.Position = UDim2.new(0.79194599390029907, 0, 0.089230768382549286, 0)
ShhBTN.Rotation = 0
ShhBTN.Selectable = true
ShhBTN.SelectionOrder = 0
ShhBTN.Size = UDim2.new(0.19288010895252228, 0, 0.29076939821243286, 0)
ShhBTN.SizeConstraint = Enum.SizeConstraint.RelativeXY
ShhBTN.Visible = true
ShhBTN.ZIndex = 1
ShhBTN.Font = Enum.Font.Bodoni
ShhBTN.LineHeight = 1
ShhBTN.MaxVisibleGraphemes = -1
ShhBTN.RichText = false
ShhBTN.Text = "Inject code on the data store"
ShhBTN.TextColor3 = Color3.fromRGB(0, 0, 0)
ShhBTN.TextScaled = true
ShhBTN.TextSize = 8
ShhBTN.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
ShhBTN.TextStrokeTransparency = 1
ShhBTN.TextTransparency = 0
ShhBTN.TextTruncate = Enum.TextTruncate.None
ShhBTN.TextWrapped = true
ShhBTN.TextXAlignment = Enum.TextXAlignment.Center
ShhBTN.TextYAlignment = Enum.TextYAlignment.Center
ShhBTN.AutoButtonColor = true
ShhBTN.Modal = false
ShhBTN.Style = Enum.ButtonStyle.Custom

TextBox.Archivable = true
TextBox.Active = true
TextBox.AnchorPoint = Vector2.new(0, 0)
TextBox.AutomaticSize = Enum.AutomaticSize.None
TextBox.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
TextBox.BackgroundTransparency = 0
TextBox.BorderColor3 = Color3.fromRGB(0, 0, 0)
TextBox.BorderMode = Enum.BorderMode.Outline
TextBox.BorderSizePixel = 1
TextBox.ClipsDescendants = false
TextBox.Interactable = true
TextBox.LayoutOrder = 0
TextBox.Position = UDim2.new(0.026291690766811371, 0, 0.036923076957464218, 0)
TextBox.Rotation = 0
TextBox.Selectable = true
TextBox.SelectionOrder = 0
TextBox.Size = UDim2.new(0.74113816022872925, 0, 0.64246147871017456, 0)
TextBox.SizeConstraint = Enum.SizeConstraint.RelativeXY
TextBox.Visible = true
TextBox.ZIndex = 1
TextBox.Font = Enum.Font.Bodoni
TextBox.LineHeight = 1
TextBox.MaxVisibleGraphemes = -1
TextBox.RichText = false
TextBox.Text = ""
TextBox.TextColor3 = Color3.fromRGB(0, 0, 0)
TextBox.TextScaled = false
TextBox.TextSize = 25
TextBox.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
TextBox.TextStrokeTransparency = 1
TextBox.TextTransparency = 0
TextBox.TextTruncate = Enum.TextTruncate.None
TextBox.TextWrapped = true
TextBox.TextXAlignment = Enum.TextXAlignment.Left
TextBox.TextYAlignment = Enum.TextYAlignment.Top
TextBox.ClearTextOnFocus = false
TextBox.MultiLine = false
TextBox.PlaceholderColor3 = Color3.fromRGB(128, 128, 128)
TextBox.PlaceholderText = "Execute Any script"
TextBox.TextEditable = true

EXEBTN.Archivable = true
EXEBTN.Active = true
EXEBTN.AnchorPoint = Vector2.new(0, 0)
EXEBTN.AutomaticSize = Enum.AutomaticSize.None
EXEBTN.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
EXEBTN.BackgroundTransparency = 0
EXEBTN.BorderColor3 = Color3.fromRGB(0, 0, 0)
EXEBTN.BorderMode = Enum.BorderMode.Outline
EXEBTN.BorderSizePixel = 1
EXEBTN.ClipsDescendants = false
EXEBTN.Interactable = true
EXEBTN.LayoutOrder = 0
EXEBTN.Position = UDim2.new(0.015412169508635998, 0, 0.71384614706039429, 0)
EXEBTN.Rotation = 0
EXEBTN.Selectable = true
EXEBTN.SelectionOrder = 0
EXEBTN.Size = UDim2.new(0.37051761150360107, 0, 0.23846158385276794, 0)
EXEBTN.SizeConstraint = Enum.SizeConstraint.RelativeXY
EXEBTN.Visible = true
EXEBTN.ZIndex = 1
EXEBTN.Font = Enum.Font.Bodoni
EXEBTN.LineHeight = 1
EXEBTN.MaxVisibleGraphemes = -1
EXEBTN.RichText = false
EXEBTN.Text = "EXE"
EXEBTN.TextColor3 = Color3.fromRGB(0, 0, 0)
EXEBTN.TextScaled = true
EXEBTN.TextSize = 8
EXEBTN.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
EXEBTN.TextStrokeTransparency = 1
EXEBTN.TextTransparency = 0
EXEBTN.TextTruncate = Enum.TextTruncate.None
EXEBTN.TextWrapped = true
EXEBTN.TextXAlignment = Enum.TextXAlignment.Center
EXEBTN.TextYAlignment = Enum.TextYAlignment.Center
EXEBTN.AutoButtonColor = true
EXEBTN.Modal = false
EXEBTN.Style = Enum.ButtonStyle.Custom

InjectSafeBTN.Archivable = true
InjectSafeBTN.Active = true
InjectSafeBTN.AnchorPoint = Vector2.new(0, 0)
InjectSafeBTN.AutomaticSize = Enum.AutomaticSize.None
InjectSafeBTN.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
InjectSafeBTN.BackgroundTransparency = 0
InjectSafeBTN.BorderColor3 = Color3.fromRGB(0, 0, 0)
InjectSafeBTN.BorderMode = Enum.BorderMode.Outline
InjectSafeBTN.BorderSizePixel = 1
InjectSafeBTN.ClipsDescendants = false
InjectSafeBTN.Interactable = true
InjectSafeBTN.LayoutOrder = 0
InjectSafeBTN.Position = UDim2.new(0.7164236307144165, 0, 0.71384614706039429, 0)
InjectSafeBTN.Rotation = 0
InjectSafeBTN.Selectable = true
InjectSafeBTN.SelectionOrder = 0
InjectSafeBTN.Size = UDim2.new(0.27674004435539246, 0, 0.24000005424022675, 0)
InjectSafeBTN.SizeConstraint = Enum.SizeConstraint.RelativeXY
InjectSafeBTN.Visible = true
InjectSafeBTN.ZIndex = 1
InjectSafeBTN.Font = Enum.Font.Bodoni
InjectSafeBTN.LineHeight = 1
InjectSafeBTN.MaxVisibleGraphemes = -1
InjectSafeBTN.RichText = false
InjectSafeBTN.Text = "Inject safe mode"
InjectSafeBTN.TextColor3 = Color3.fromRGB(0, 0, 0)
InjectSafeBTN.TextScaled = true
InjectSafeBTN.TextSize = 8
InjectSafeBTN.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
InjectSafeBTN.TextStrokeTransparency = 1
InjectSafeBTN.TextTransparency = 0
InjectSafeBTN.TextTruncate = Enum.TextTruncate.None
InjectSafeBTN.TextWrapped = true
InjectSafeBTN.TextXAlignment = Enum.TextXAlignment.Center
InjectSafeBTN.TextYAlignment = Enum.TextYAlignment.Center
InjectSafeBTN.AutoButtonColor = true
InjectSafeBTN.Modal = false
InjectSafeBTN.Style = Enum.ButtonStyle.Custom

ExeUI.Name = "ExeUI"
ClearBTN.Name = "ClearBTN"
UIGradient.Name = "UIGradient"
InjectbackBTN.Name = "InjectbackBTN"
ShhBTN.Name = "ShhBTN"
TextBox.Name = "TextBox"
EXEBTN.Name = "EXEBTN"
InjectSafeBTN.Name = "InjectSafeBTN"
UIDragDetector.Name = "UIdrag"

ClearBTN.Parent = Frame
UIGradient.Parent = Frame
InjectbackBTN.Parent = Frame
ShhBTN.Parent = Frame
TextBox.Parent = Frame
EXEBTN.Parent = Frame
InjectSafeBTN.Parent = Frame
UIDragDetector.Parent = Frame

return ExeUI
