return {
	dependencies = {
	},
	package = {
		authors = {"Nowoshire"},
		description = "A Signal implementation for Luau, with a nice balance of ergonomics, performance, and features.",
		homepage = "https://nowoshire.github.io/NamedSignal/",
		include = {"*", "wally.toml"},
		license = "MIT",
		name = "nowoshire/namedsignal",
		realm = "shared",
		registry = "https://github.com/UpliftGames/wally-index",
		repository = "https://github.com/Nowoshire/NamedSignal",
		version = "2.0.4",
	},
}
