name: Build RBXMX Release

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build RBXMX
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Rojo
        run: |
          cargo install rojo

      - name: Check Rojo
        run: |
          rojo --version

      - name: Validate project
        run: |
          rojo sourcemap default.project.json > sourcemap.json

      - name: Build RBXMX
        run: |
          rojo build default.project.json -o shh.rbxmx

      - name: Verify RBXMX
        run: |
          test -f shh.rbxmx
          test -s shh.rbxmx

          echo "RBXMX generado:"
          ls -lh shh.rbxmx

      - name: Generate version
        id: version
        run: |
          echo "version=v1.0.${GITHUB_RUN_NUMBER}" >> "$GITHUB_OUTPUT"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: "RBXMX ${{ steps.version.outputs.version }}"
          generate_release_notes: true
          files: |
            shh.rbxmx
            sourcemap.json
